[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Headers para todos os arquivos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "upgrade-insecure-requests; default-src 'self' * data: blob: 'unsafe-inline' 'unsafe-eval'; style-src 'self' * 'unsafe-inline'; style-src-elem 'self' * 'unsafe-inline'; font-src 'self' * data:; script-src 'self' * 'unsafe-inline' 'unsafe-eval'; script-src-elem 'self' * 'unsafe-inline' 'unsafe-eval'; connect-src 'self' * data:; img-src 'self' * data: blob:; frame-src *; worker-src 'self' blob:;"

# Headers para arquivos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "text/html; charset=utf-8"

# Headers para imagens
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para fontes
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers para o service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript; charset=utf-8"

# Headers para o manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json; charset=utf-8"

# Headers para arquivos Astro
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

# Redirecionamentos
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    
    [[plugins.inputs.audits]]
      path = "/"
      
    [[plugins.inputs.audits]]
      path = "/index.html" 